// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkedahmnkjhqcjtfbwaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZWRhaG1ua2pocWNqdGZid2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDM1NTksImV4cCI6MjA3MTE3OTU1OX0.IR6PT17nDj_UupNHUHXjnbaefIRwV1GaqDMcCwAwaU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});